### ISSUE TITLE
Possibly unicode category is missing for `[Uu]` code in the documentation

### ISSUE THREAD

**Issue by aleksmelnikov** [cenotelie/hime-grams#1]
I 've found `[Uu]` code in the `csharp.gram`:
```
// A.1.8 Literals
		INTEGER_LITERAL_DECIMAL		-> ('0' | [1-9] [0-9]*) ([Uu] [Ll]? | [Ll] [Uu]? )? ;
```
Please, could you add a unicode category for it in the [docs](https://cenotelie.fr/projects/hime/reference/lang-ucategories)?

**Comment by woutersl** [comment]
`[Uu]` here is not a unicode category, it is a [character class](https://cenotelie.fr/projects/hime/reference/lang-terminals#Class). In this case, it describes a class where characters can be either `U` or `u`. Here it is equivalent to `('U' | 'u')`.

**Comment by aleksmelnikov** [comment]
thx
